name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - master  # Ou qualquer outra branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente onde o job será executado
    steps:
    # 1. Verifica o repositório
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Configura o Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 3. Cache das camadas do Docker para acelerar o processo de build
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # 4. Realiza o build da imagem Docker
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/protasker .
    ##docker build -t ${{ secrets.DOCKER_USERNAME }}/protasker:${{ github.sha }} .

    # 5. Realiza o login no Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. Envia a imagem para o Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/protasker
    ##docker push ${{ secrets.DOCKER_USERNAME }}/protasker:${{ github.sha }}
